### ISSUE TITLE
关于如何运行

### ISSUE THREAD

**Issue by haohuancheng** [lijiarui/microsoft-summit-chatbot-course#1]
您好！我除了按如下步骤操作外，是不是还要在代码中修正一些定制配置信息呢？

git clone git@github.com:lijiarui/chatbot-zero-to-one.git
cd chatbot-zero-to-one
npm install
npm start

**Comment by lijiarui** [comment]
请把详细的错误信息展示一下，方便我帮你查看问题。

**Comment by huan** [comment]
Close this issue due to no response for months.
